version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    volumes:
      - ./:/go/src
    tty: true

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    # command: -host 0.0.0.0 -port 8123 -queue "${CLOUD_TASKS_PARENT}/queues/test"
    command: -host 0.0.0.0 -port 8123
    ports:
      - "${TASKS_PORT:-8123}:8123"
    env_file:
      - .env

networks:
  backend:
    external: false
